timer_start:
  alias: Timer Start
  mode: single
  sequence:
  - service: timer.start
    data_template:
      duration: "{{ duration }}"
    target:
      entity_id: "{{ entity_id }}"
timer_stop:
  alias: Timer Stop
  mode: single
  sequence:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ states(entity_id) == 'active' }}"
        alias: Specific timer is active
      sequence:
      - service: timer.cancel
        target:
          entity_id: "{{ entity_id }}"
        alias: Cancel specific timer
    - conditions:
      - condition: or
        conditions:
        - condition: template
          value_template: "{{ (states.timer|selectattr('state','eq','active')|list|length == 1 and entity_id == 'null') }}"
          alias: Null and only 1 active
        - condition: template
          value_template: "{{ (entity_id == ''timer.timer1, timer.timer2, timer.timer3'') }}"
          alias: Stop all timers
        alias: Only 1 timer or all timers
      sequence:
      - service: timer.cancel
        target:
          entity_id:
          - timer.timer1
          - timer.timer2
          - timer.timer3
        alias: Cancel all timers
    default:
    - stop: ""
