timer_start:
  alias: Timer Start
  mode: single
  sequence:
  - service: timer.start
    data_template:
      duration: "{{ duration }}"
    target:
      entity_id: "{{ 'timer.' + entity_id }}"
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: "{{ 'input_boolean.' + entity_id }}"
timer_stop:
  alias: Timer Stop
  mode: single
  sequence:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ states('timer.' + entity_id) == 'active' }}"
        alias: Specific timer is active
      sequence:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.{{ entity_id }}
    - conditions:
      - condition: or
        conditions:
        - condition: template
          value_template: "{{ (states.timer|selectattr('state','eq','active')|list|length == 1 and entity_id == 'null') }}"
          alias: Null and only 1 active
        - condition: template
          value_template: "{{ (entity_id == 'all') }}"
          alias: Stop all timers
        alias: Only 1 timer or all timers
      sequence:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id:
          - input_boolean.timer1
          - input_boolean.timer2
          - input_boolean.timer3
    default:
    - stop: ''
