language: "nl"
intents:
  TimerDuration:
    data:
      - sentences:
          - "(hoe lang|hoeveel tijd) nog op de {entity_id} timer"
          - "hoe lang duurt de {entity_id} timer nog"
      - sentences:
          - "(hoe lang|hoeveel tijd) nog op de timer[s]"
          - "hoe lang [duurt|duren] de timer[s] nog"
        slots:
          entity_id: "null"
lists:
  entity_id:
    values:
      - in: "eerste"
        out: "timer.timer1"
      - in: "tweede"
        out: "timer.timer2"
      - in: "derde"
        out: "timer.timer3"
      - in: "(alle|iedere)"
        out: "timer.timer1, timer.timer2, timer.timer3"
